{% set name = "fortran_stdlib" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fortran-lang/stdlib/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6581cbb533d59be3da0c6b8dc9cfedbc5a1db22af1f555c3ecb8f3b87fc26a49

build:
  number: 0
  skip: true  # [win]
  script:
    - >
      cmake ${CMAKE_ARGS} -DBUILD_SHARED_LIBS=ON -G Ninja -B _build -DWITH_QP=OFF  # [build_platform != target_platform] -DWITH_XDP=OFF  # [build_platform != target_platform] -DBUILD_TESTING=OFF  # [build_platform != target_platform] -Df03real128_EXITCODE=0  # [build_platform != target_platform] -Df03real128_EXITCODE__TRYRUN_OUTPUT=""  #
      [build_platform != target_platform]
    - cmake --build _build
    - ctest --test-dir _build --output-on-failure --parallel  # [build_platform == target_platform]
    - cmake --install _build

  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - ninja
    - fypp

test:
  requires:
    - pkg-config
  commands:
    - pkg-config {{ name }} --exact-version {{ version }}
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}

about:
  home: https://github.com/fortran-lang/stdlib
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  summary: Fortran standard library
  doc_url: https://stdlib.fortran-lang.org
  dev_url: https://github.com/fortran-lang/stdlib

extra:
  recipe-maintainers:
    - awvwgk
    - mardiehl
